services:
  - type: web
    name: household-assistant-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyCeVbnjwIbfrYgf3xTCRIHkdC3fGi6zV-Y
